use anyhow::Result;
use std::fs;
use std::io::Write;

use crate::parser::SchemaDefinition;

pub fn read_schema_file(path: &str) -> Result<String> {
  Ok(fs::read_to_string(path)?)
}

pub fn write_tables_to_file(tables: &[SchemaDefinition], output_path: &str) -> Result<()> {
  let mut file = fs::File::create(output_path)?;

  writeln!(file, "# This file was generated by ais. Do not edit manually!\n")?;

  for td in tables {
    writeln!(file, "{}\n", td.content)?;
  }

  Ok(())
}
